version: '3.9'

services:
  node:
    image: dockercommands
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - APP_VERSION=1.0
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_SERVER=${MONGO_SERVER}
      - MONGO_DB=${MONGO_DB}
    depends_on: 
      - mongodb
      
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db:/data/db

volumes:
  db:

