version: '3.9'

services:
  node:
    image: dockercommands
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_VERSION=${APP_VERSION}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_SERVER=mongodb
      - MONGO_DB=funWithDocker
    depends_on: 
      - mongodb
      
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db:/data/db

volumes:
  db:

